# 第３章 Rのオブジェクト

## 3.1 アトミックベクトル
アトミックベクトルは単純な**データのベクトル**のこと。<br>
アトミックベクトルは一次元ベクトルとして値を格納しています。<br>
そしてアトミックベクトルは同じデータ型のみを扱います。<br>

In [5]:
die <- c(1,2,3,4,5,6)
five <- 5

In [6]:
is.vector(die)
is.vector(five)

[1] TRUE

[1] TRUE

今回紹介するデータ型は以下のものです。<br>
他にも色々なものがあった……気がするけど、とりあえずこれだけでOK


| データ型                   | 例         |
| :------------------------- | ---------- |
| Double(倍精度浮動小数点型) | 3.14       |
| Integer(整数)              | 100        |
| Character(文字)            | "にゃーん" |
| Logical(論理値)            | TRUE       |
| Complex(複素数)            | 4i         |
| Raw(バイナリ)              |      00      |

### 倍精度浮動小数点型
通常の数値のデータはこれ。<br>
正でも負でも小数点以下でもOK。<br>

In [10]:
die <- c(1,2,3,4,5,6)
ensyu <- 3.14

In [12]:
typeof(die)
typeof(ensyu)

[1] "double"

[1] "double"

### 整数
小数がない数字。<br>
ぶっちゃけ「２」や「１０」といった数字も倍精度小数点型でいけるので<br>
整数型を扱う機会は多くはない……はず。<br>
<br>
整数型のオブジェクトを意図的に作成したい時は、<br>
数値の後ろに **L** をつけることで作成することが可能。

In [16]:
syosu <- c(1,2,3,4)
int <- c(1L,2L,3L,4L)
int6 <- c(1:6)

In [17]:
typeof(syosu)
typeof(int)
typeof(int6)

[1] "double"

[1] "integer"

[1] "integer"

### 文字型
文字型は何かしろのテキストを格納することのできるデータ型です。<br>
シングルクウォートかダブルクウォートで囲んでください。<br>
クウォートで囲んであれば数字だろうが文字型として認識します。<br>
<br>
クウォートを忘れると、（おそらくは）存在しない変数を探してErrorが出るはず。

In [20]:
a <- 'hello'
b<- "１２３１２３"

In [22]:
#クウォート忘れると、このざま
b <- reiwa

ERROR: Error in eval(expr, envir, enclos): object 'reiwa' not found


In [21]:
typeof(a)
typeof(b)

[1] "character"

[1] "character"

### 論理値型
要するにブーリアン。<br>
Rにおける論理値の **TRUE** か **FALSE** を格納します。<br>
双方共に、TとFで省略が可能。

In [23]:
logic <- c(TRUE,FALSE,F,T)

In [24]:
typeof(logic)

[1] "logical"

### 複素数とraw
まず使わない。<br>
けど一応紹介します。<br>
<br>
複素数ベクトル作成する時は、数値に i を追加したものを書けば、<br>
虚数項として認識するので、複素数ベクトルを作れます。<br>
<br>
rawベクトルは手が加えられていないデータバイトなどを格納するデータ型。<br>
`raw(n)`で作成することができる……けどrawのヘルプ見て。~~よくわかんないから~~<br>

In [25]:
comp <- c(1+1i , 2+2i , 3+3i)
bainari <- raw(10)

In [26]:
typeof(comp)
typeof(bainari)

[1] "complex"

[1] "raw"

## 3.2 属性
属性はアトミックベクトルに追加することができる情報のこと<br>
オブジェクトの値を邪魔しない上、オブジェクトを表示しても表示されないメタデータ。<br>
<font color = "red">ここに表を書く

### 3.2.1 名前


In [32]:
die <- c(1,2,3,4,5,6)

names(die)

NULL

In [34]:
names(die) <- c("one","tow","three","four","five","six")
names(die)

[1] "one"   "tow"   "three" "four"  "five"  "six"

In [40]:
attributes(die)
print("==========================")
die

$names
[1] "one"   "tow"   "three" "four"  "five"  "six"

[1] "=========================="


one   tow three  four  five   six 
    1     2     3     4     5     6

In [41]:
#  attributesは値に影響を与えません。
die + 1

one   tow three  four  five   six 
    2     3     4     5     6     7

In [43]:
# namesでの再定義が可能。
names(die) <- c("ichi","ni","san","shi","go","roku")
die

ichi   ni  san  shi   go roku 
   1    2    3    4    5    6

### 3.2.2 次元

In [47]:
dim(die) <- c(2,3)
die

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [50]:
dim(die) <- c(1,2,3)
print(die)

, , 1

     [,1] [,2]
[1,]    1    2

, , 2

     [,1] [,2]
[1,]    3    4

, , 3

     [,1] [,2]
[1,]    5    6



## 3.3 行列
線形代数みたいに２次元のデータを格納する。<br>
`matrix()`関数を使用することで作成が可能。

In [53]:
m <- matrix(die)
print(m)

     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5
[6,]    6


In [55]:
m <- matrix(die , ncol = 3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [57]:
m <- matrix(die,nrow = 3)
print(m)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


## 3.4 配列
`array()`はn次元配列を作成します。<br>

In [63]:
ar <- array(c(11:14,21:24,31:34) , dim=c(2,2,3))
print(ar)

, , 1

     [,1] [,2]
[1,]   11   13
[2,]   12   14

, , 2

     [,1] [,2]
[1,]   21   23
[2,]   22   24

, , 3

     [,1] [,2]
[1,]   31   33
[2,]   32   34



## 3.5 クラス
アトミックベクトルの特殊系。<br>
例えば`die`は倍精度浮動小数点型で記
(詳しいことは「第三部 スロットマシン」で解説するのでとりあえず置いておこう。)<br>

### 3.5.1 日付
Rの属性システムのおかげで、色々なデータ型を表現することが可能です。<br>
Rは日付と時刻を表現するために特別なクラスを使用しています。<br>

In [72]:
now <- Sys.time()
now
typeof(now)
class(now)

[1] "2019-04-24 08:18:05 UTC"

[1] "double"

[1] "POSIXct" "POSIXt"

出力に`POSIXct`と表示されました。<br>
これは日付や時刻を表現するために使用されているフレームワークです。<br>
POSIXctで個々の時刻は起点である1970年1月1日午前0時からの秒数で表現されています。<br>
unclassを使用して中身を見ることが可能です。

In [74]:
# POSIXctの元データ
unclass(now)
typeof(unclass(now))

[1] 1556093885

[1] "double"

この`POSIXct`と`POSIXt`の二つを設定することで

### 3.5.2 ファクタ
ファクタは分類情報を格納するための手段です。<br>
ファクタを作成するにはfactor関数にアトミックベクトルを渡します。<br>
Rはベクトルに含まれているデータを整数として改めて符号化して整数ベクトルにその結果を格納します。<br>


In [19]:
gender <- factor(c("male","female","female","male"))

typeof(gender)

[1] "integer"

In [20]:
attributes(gender)

$levels
[1] "female" "male"  

$class
[1] "factor"

unclassを使用することでRがファクタをどのように扱っているかわかります。

In [21]:
unclass(gender)

[1] 2 1 1 2
attr(,"levels")
[1] "female" "male"

## 3.6 型強制

In [1]:
sum(c(T,T,F,F))

[1] 2

as関数を使用することで、明示的にデータ型を変更することが可能です。

In [4]:
as.character(100)
as.logical(1)
as.numeric(FALSE)

[1] "100"

[1] TRUE

[1] 0

## 3.7 リスト
アトミックベクトルは単一のデータ型を扱うが、<br>
リストは複数のデータをまとめることが可能である。

In [7]:
list1 <- list(100:130 ,"R",list(TRUE,FALSE))
print(list1)

[[1]]
 [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120 121 122 123 124 125 126 127 128 129 130

[[2]]
[1] "R"

[[3]]
[[3]][[1]]
[1] TRUE

[[3]][[2]]
[1] FALSE




***
**練習問題**<br>
リストを使用して、値1を持つハートのエースのようなトランプカードを格納してください。

In [10]:
card <- list("ace" , "hearts", 1)
print(card)

[[1]]
[1] "ace"

[[2]]
[1] "hearts"

[[3]]
[1] 1



## 3.8 データフレーム
リストの２次元バージョン。<br>
ベクトルの長さを同一にする必要があるため、注意。

In [11]:
df <- data.frame(face = c("ace","tow", "six"),
                suit = c("clubs","clubs","clubs"),
                value = c(1,2,3))

df

face suit  value
1 ace  clubs 1    
2 tow  clubs 2    
3 six  clubs 3

In [12]:
typeof(df)

[1] "list"

In [13]:
class(df)

[1] "data.frame"

In [14]:
str(df)

'data.frame':	3 obs. of  3 variables:
 $ face : Factor w/ 3 levels "ace","six","tow": 1 3 2
 $ suit : Factor w/ 1 level "clubs": 1 1 1
 $ value: num  1 2 3


## 3.9 データのロード

In [16]:
deck <- read.csv("deck.csv")
head(deck)

face  suit   value
1 king  spades 13   
2 queen spades 12   
3 jack  spades 11   
4 ten   spades 10   
5 nine  spades  9   
6 eight spades  8

## 3.10 データの保存 

In [17]:
write.csv(deck , file = "cards.csv" , row.names = FALSE)